### ISSUE TITLE
error - ApolloError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by ryan2nguyen** [arafat4693/portfolio#2]
My steps are the same as [KarthikSwaminathan's](https://github.com/arafat4693/portfolio/issues/1#issue-1580904869) but error is **Only absolute URLs are supported**. 
<img width="1203" alt="Screenshot 2023-02-13 at 10 49 19" src="https://user-images.githubusercontent.com/115521188/218366247-fa70c67b-2e57-4574-a4a6-c85c627444f4.png">

**Comment by arafat4693** [comment]
Can you share the URL here?
