### ISSUE TITLE
NextJS Router

### ISSUE THREAD

**Issue by Brayan-724** [arafat4693/portfolio#3]
# Why?
[Your Code](https://github.com/arafat4693/portfolio/blob/main/pages/index.tsx#L78-L110)
You aren't use the powerful **NextJS Router**. Why?
The **animation also can be used** with that and will be **very organized**. 
On the NextJS Router exists a event that can be used for detect the route change and it's more precise because it has two steps ("start", "end"), with that you can init the animation with the start call and same with end.
Other reason for use NextJS Router is the SEO, you should have a unique title for each page, with NextJS Router you can use the `<Head />` component and on the build step it will be placed at the `html > head`.
The last and most important reason, using by this way is like you don't know how to use the NextJS Router.

**Comment by arafat4693** [comment]
Thanks, man, for letting me know this. I made a mistake not using nextjs router. I tried it. However, I failed miserably with the animation, so I went without the nextjs router. It's too late to change now.

**Comment by Brayan-724** [comment]
Okay. The last reason, it's just a joke.
