### ISSUE TITLE
hygraph Schema 

### ISSUE THREAD

**Issue by Cuongtau** [arafat4693/portfolio#4]
Can u share your Hygraph schema or publish your hygraph url and token

**Comment by arafat4693** [comment]
Use this URL to clone the complete Hygraph project, including assets, contents, etc. https://app.hygraph.com/clone/61c44d5d9a2640f39c7a617d3bc6cf60?name=Portfolio

**Comment by Cuongtau** [comment]
Thanks bro <3

**Comment by Brayan-724** [comment]
Please someone close this issue if nothing is going to happen
